libusb support for isochronous transfer on Windows composite device
libusb/libusb pull request #1227
Opened 2023-01-01 11:25 UTC by yomei-o

I succeed to work a UVC webcam on Windows.
But current version of libusb and libuvc does not work UVC .
UVC Camera use isochronous transfer.
The libusb does not support isochronous transfer  on Windows composite device.
 Then I fixed it.
And I tested two UVC devices. (isochronous transfer device and bulk transfer device)

[https://github.com/libuvc/libuvc/issues/12](https://github.com/libuvc/libuvc/issues/12)

2023-01-10 04:29 UTC, hjelmn commented on libusb/os/windows_winusb.c
> +	//bool is_using_usbccgp = (priv->apib->id == USB_API_COMPOSITE);
Please do not leave commented out code. If this line is no longer needed then remove it entirely.

2023-01-10 04:30 UTC, hjelmn commented on libusb/os/windows_winusb.c
> +			HANDLE h_proc=NULL;
nit. spaces around =

2023-01-10 04:30 UTC, hjelmn commented on libusb/os/windows_winusb.c
> +			h_proc = GetCurrentProcess();
another nit. you just set this to NULL then set it to GetCurrentProcess(); please set this at the declaration.

2023-01-10 04:31 UTC, hjelmn commented
I know nothing about the windows backend but this looks reasonable. Address the comments and I will see about merging this.

2023-01-22 21:44 UTC, tormodvolden commented on libusb/os/windows_winusb.c
> +		int ii;
Just "i" is the norm for such loop counters. "i" can also be thought of as a very short form of "interfaces".

2023-01-22 21:46 UTC, tormodvolden commented
The commit message needs to be fixed.

2023-01-22 21:49 UTC, tormodvolden commented on libusb/os/windows_winusb.c
> +	bool is_using_usbccgp = false;
The value is checked on line 2610 but I don't see it possibly changed in between.

2023-01-22 21:53 UTC, tormodvolden requested changes
Can you explain in words what these changes are doing?

2023-01-25 12:58 UTC, mcuee commented
@yomei-o 

Please help to address the comments . Thanks.

2026-05-03 09:25 UTC, mcuee commented
This PR does not seem to go anywhere. Close for now.

2026-05-03 09:37 UTC, tormodvolden commented
I am not sure I agree to closing the PR even if it is stale. There is maybe not so much work needed to get it into shape. When closed, there is less chance someone will look at it and potentially taking it further. Can we instead add a new label for these cases? Then those who want to see a PR list without this can filter it away.

2026-07-13 17:01 UTC, levicki commented
If I may add, I am using `libusbK` driver installed on camera composite parent and for me ISO transfers work with UVC cameras.

Therefore, the simplest solution for the OP problem is to replace Windows `usbccgp.sys` driver on camera composite parent with `libusbK` (that's also the only correct way I am aware of for accessing both video and audio endpoints of UVC cameras with microphone).

2026-07-13 22:48 UTC, sonatique commented
Thanks @levicki .
@mcuee @tormodvolden : the code in this PR has several problems. In my opinion this PR shall not be merged, especially since code that fix the issue is merged since 1.0.27, as far as I can tell, via PR https://github.com/libusb/libusb/pull/965 . PR #965  implements IAD-based associated-interface claiming, i.e. the general form of what this PR attempted. 

Interfaces grouped by an IAD (e.g. UVC VideoControl + VideoStreaming) now get their API backend assigned in set_composite_interface() and are claimed via WinUSB_GetAssociatedInterface(). 

@yomei-o : Please retest with libusb ≥ 1.0.27; 

Note: remaining iso-transfer quality issues are tracked in #909 #1104.

Closing as superseded rather than stale.

2026-07-13 22:48 UTC, closed without merging