Windows: Fix timeouts if only endpoint 0 exists
libusb/libusb pull request #963
Opened 2021-07-23 07:28 UTC by julianscheel

The default timeouts of 5 seconds used by WinUSB are cleared in
configure_endpoints(). This was not called if not at least one extra
endpoint apart from endpoint 0 existed, so that in those cases the
default timeout of 5 seconds remained in place.
Fix this by calling configure_endpoints, even if no interface specific
endpoints were found, so that it can configure endpoint 0.

Signed-off-by: Julian Scheel <julian@jusst.de>

2021-07-23 13:56 UTC, mcuee commented
@julianscheel Do you encounter this issue is real use case, like DFU (device FW upgrade)? What is the symptom?

2021-07-23 15:01 UTC, julianscheel commented
@mcuee Yes, faced this in a DFU implementation for an XMOS based device, where the flash erase command takes >5 seconds to execute. Thus the belonging request on endpoint 0 is blocked for more than 5 seconds and did timeout on Windows, due to the WinUSB default timeout of 5 seconds on the control endpoint.

2021-07-24 08:45 UTC, mcuee commented
@dickens @tormodvolden Please help to check if there are any side effects of this change. Thanks.

2021-07-27 09:53 UTC, tormodvolden commented
There must be something wrong with that DFU implementation. The device should not block a request while doing the flash erase, it should respond to the triggering DFU_GET_STATUS request with a _poll timeout_ value larger than the time that it expects to be busy erasing, then the host will wait for the specified time and pick up communication afterwards.

2021-07-27 11:29 UTC, julianscheel commented
@tormodvolden Sure, but even then, the 5.0 second timeout is only existent on Windows, while on macOS and Linux there is no 5.0 second timeout. So for consistency between platforms using libusb I actually think it would make sense to clear that timeout. 

And furthermore whenever you have a second endpoint activated it actually is cleared already. The only case where that timeout remains in place is when only endpoint 0 is used.

2021-07-27 13:41 UTC, tormodvolden commented
Yes, I agree to consistency. But you should still "complain" to the device bootloader authors/distributors and try get them fix it.

2021-07-28 08:52 UTC, mcuee commented
@tormodvolden Since you have lots of experiences with DFU as the maintainer of dfu-util, just wondering how often you see reports of such type of dfu devices.

2021-07-28 13:35 UTC, mcuee commented
@tormodvolden It seems to me the patch is safe to be merged. Do you agree?

2021-08-29 19:18 UTC, tormodvolden commented
I don't know much details of the Windows API, but this change seems to make sense and should be safe AFAICS. You are however not checking the return value `r` like is done in the case of several endpoints. Instead of duplicating this it might make sense to put the existing multiple endpoint code in an "else" clause and let it finish off the same in both cases.

2021-08-29 19:39 UTC, tormodvolden commented
@mcuee Often DFU implementations are broken one way or another, and this example of wrongly suspending a USB transaction while flashing or erasing is not unique. Further, DFU devices (in DFU mode) should only use the control endpoint and not have other endpoints in the interfaces (they often have multiple alternate settings), so this endpoint initialisation would go missed everywhere FWIW. But in the case of dfu-util it specifically sets the timeout to 5 seconds on all platforms, so this change wouldn't make any difference for the timeout in the end.

2021-08-30 03:39 UTC, mcuee commented
@tormodvolden Thanks for the explanation for the common pitfalls of DFU devices.

2021-09-22 11:44 UTC, tormodvolden requested changes
You are not checking the return value r like is done in the case of several endpoints. Instead of duplicating this it might make sense to put the existing multiple endpoint code in an "else" clause and let it finish off the same in both cases.

2021-10-02 09:48 UTC, tormodvolden approved these changes

2021-10-02 09:52 UTC, tormodvolden commented
I have addressed my previously requested changes in my rework at https://github.com/tormodvolden/libusb/commit/9db6ff8f6032e60e22254b6429ae7e62a832152f but I'd like additional reviews and approvals of this.

2021-11-07 12:00 UTC, closed without merging